### ISSUE TITLE
More robust with -RL

### ISSUE THREAD

**Issue by pepa65** [jreinert/hless#2]
I've had problems displaying bash sources, until I found that instead of `"-R"` to give `"-RL"` as the first option to `less` and it started working.

**Comment by repomaa** [comment]
cool thanks for the info. Wanna make a PR out of it?

**Comment by pepa65** [comment]
For the honour of it you mean? Or for a proper workflow??

**Comment by repomaa** [comment]
Both :)

**Comment by pepa65** [comment]
I don't mind if you do it. I would need to fork your repo, then clone again, etc. etc.
